server:
  port: 8081
app:
  endpoints:
    city-data-server: city-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-db}/city_api
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

