server:
  port: 8081
app:
  endpoints:
    city-data-server: city-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/city_api
    username: user
    password: password